# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1878b2c13036836c438db2c72600ae1efaf97c0954d0830f7f9143d11ce29d7f8ac62479458f6e7cfccbaf3d0148ef7eccb62d8a96a9ce1a720207ad65db5a22

test:
  secret_key_base: 27e5da0efe62aa017c742d45da8f4528fae766104fd4fff62adcae7ec874cdb4863c2ff72bb901d101d6cf75156ef96bd56db0131e23d34d50f50b309fd33179

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
